### ISSUE TITLE
Disconnect handler triggers a JS error in IE8

### ISSUE THREAD

**Issue by AD7six** [Flotype/now#103]
As can be seen here: ![IE8 being beautiful as usual](http://ad7six.com/dump/now-IE8-js-error.png)

The disconnect handler code triggers an error in IE8. Not sure of a correct fix, so none suggested at this time.

**Comment by tommedema** [comment]
should this not be `typeof(obj[i]) === 'object'` ?

**Comment by ericz** [comment]
typeof also works without the parenthesis (in IE as well as other browsers). The issue I believe is that `seen` appears to be an object and not an array -- as seen in the "locals" panel on the right side of the screenshot, which would make `.indexOf` throw the exception

**Comment by AD7six** [comment]
that pesky comment & close button ... :)

**Comment by ericz** [comment]
Haha yepp

**Comment by steveWang** [comment]
The issue here is really that IE 8 doesn't define Array.indexOf. Presumably commit 4bcd30668ff97179257703d030c1aad221516745 fixed this.

**Comment by AD7six** [comment]
Presuming is no substitute for testing :)

While the specific error reported in the ticket is nolonger generated, it's simply replaced with "Error: Out of memory"

Since I can't reopen the ticket I trust someone on the team will.

**Comment by steveWang** [comment]
More specifics would be nice. And it's a bit difficult to test IE without Windows, but it's a bit difficult to develop with Windows. ;D

**Comment by AD7six** [comment]
I know - every time I open my VM I feel a part of me dies. Then I open IE and a bit more of me follows.

I don't have anything more specific to add; I could do another screenshot but all it would show is the text "Error: Out of memory" in the console of developer tools.

The most detailed I can be is: In IE on the master branch (with that one commit cherry-picked) if the node server is killed/restarted the text "Error: Out of memory" (alone, no file reference) is printed to the console. and it's 100% reproducible.

**Comment by ericz** [comment]
Hey AD7six, I'll look into this today. 

Thanks for staying diligent. Definitely appreciate it.

**Comment by steveWang** [comment]
Wow, I feel stupid. Fixed in 4766fe501d8d43b99a56d241f1631f422094d684.
