### ISSUE TITLE
IE8 sometimes generates errors in remoteCall

### ISSUE THREAD

**Issue by AD7six** [Flotype/now#108]
As shown in this screenshot:

![IE8 error in remoteCall](http://ad7six.com/dump/IE8-remoteCall.png)

the variable theFunction sometimes is not a function (in this case false) and therefore triggers a js error.

**Comment by ericz** [comment]
Thanks for the report. Looking into it..

**Comment by ericz** [comment]
This should be fixed in the latest 0.7

If you're still having issues with this let me know AD7six
