### ISSUE TITLE
Minor issue: add now.ready to examples

### ISSUE THREAD

**Issue by j03m** [Flotype/now#113]
I struggled for a bit trying to figure out a client side error that seemed timing related. for example, in the helloworld sample, take the call to distributeMessage and copy it into .ready(). This will cause an error stating that distributeMessage is not a part of object now. This is because document.ready seems to fire before now.ready. 

Took me a while to find now.ready in the doc - might be worth dropping it into the samples.

Other then that - this thing rocks. Peace peeps.

**Comment by ericz** [comment]
We added now.ready docs here: http://www.nowjs.com/doc/now

But still need to add more examples / use in examples now.ready

We'll add some more examples soon including ones using now.ready.
