### ISSUE TITLE
nowjs on secure (https) server problem

### ISSUE THREAD

**Issue by czajah** [Flotype/now#118]
I'm including now.js this way:

&lt;script type="text/javascript" src="HTTPS://localhost:3000/nowjs/now.js">&lt;/script>

and it is ok but a problem is with automagic including socket.io.js because it is accessed via HTTP:

(The page at HTTPS://localhost:3000/szop ran insecure content from HTTP://localhost:3000/socket.io/socket.io.js.)

so GET http://localhost:3000/socket.io/socket.io.js  fails.

**Comment by steveWang** [comment]
Couple of things that you'll need to change manually for this to work:

Line 434:

```
socket = new io.Socket('**SERVER**', {port: **PORT**, secure: true});
```

Line 453:

```
fileref.setAttribute("src", "//**SERVER**:**PORT**"+dependencies[i]['path']);
```

**Comment by czajah** [comment]
which file?

**Comment by steveWang** [comment]
now.js

**Comment by czajah** [comment]
ok, its something like this:

``` javascript
socket = new io.Socket('**SERVER**', {port: **PORT**,secure:"https"==scheme});
```

and

``` javascript
fileref.setAttribute("src", scheme+"://**SERVER**:**PORT**"+dependencies[i]['path']);
```

is there better way to obtain scheme/protocol name than

``` javascript
var scheme = function()
{
  var scripts = document.getElementsByTagName( 'script' );
  var srcUrlString = scripts[ scripts.length -1 ].src;

  // http://labs.apache.org/webarch/uri/rfc/rfc3986.html#regexp
  var urlParser = /^(([^:/?#]+):)?(\/\/([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?/; 
  var splitResult = srcUrlString.split(urlParser);

  return splitResult[2];
}();
```

?

**Comment by steveWang** [comment]
The first part is good. The second part should just be what I said before. Don't bother trying to make some complicated regex that handles everything for you.

**Comment by czajah** [comment]
wow, i see :) lol

**Comment by czajah** [comment]
thank you
