### ISSUE TITLE
No WebSockets on Chrome dev channel

### ISSUE THREAD

**Issue by andrewseddon** [Flotype/now#126]
Note web socket connection on Chrome dev channel is broken as of 14.0.835. You can track the issue here

https://github.com/LearnBoost/socket.io/issues/429

if it's causing you problems.

**Comment by ericz** [comment]
Yep. Thanks for the notice.

**Comment by Philipp15b** [comment]
Should be fixed in 0.8.0: https://github.com/LearnBoost/socket.io/blob/master/History.md

**Comment by ericz** [comment]
Thanks for reporting. Socket.io 0.8.X have solved these issues. Closing
