### ISSUE TITLE
Feature request - private 1 to 1 messaging

### ISSUE THREAD

**Issue by inator** [Flotype/now#129]
Use case involves a user initiating communication to another user - therefore creating a dynamic private group for chatting.  Ideally, there would be a function that takes a user array as an input parameter and returns a private group identifier that can then have chat entries directed to it without a general broadcast.

**Comment by steveWang** [comment]
For one-to-one communication, it is possible to get by with just `nowjs.getClient(clientId, callback)` (see [API docs](http://nowjs.org/jsdoc/symbols/nowjs.html#getClient) for more specifics), and for the second part of the request, well, that's what groups are for:

```
nowjs.generateGroup = function (id, arr) {
  var g = nowjs.getGroup(id);
  for (var i = 0; i < arr.length; i++) {
    g.addUser(arr[i]);
  }
  return g;
};
```

**Comment by ericz** [comment]
Let me know if you need further help on this issue @inator.

Closing
