### ISSUE TITLE
Variable syncing not working?

### ISSUE THREAD

**Issue by JeromeParadis** [Flotype/now#131]
Hello,

trying out the multiroom chat server example. Using nowjs installed from npm yesterday.
In the example, the changeRoom server function sets this.now.room to the new room name. Shouldn't the now.room variable in the client be updated with the new room name? Using Firefox and Firebug on Mac, I can see the now.room variable always stay to room1. From what I understand from the variable syncing documentation, shouldn't be now.room on the client who initiated the room change be equal to "room2" when changing to room2?

Maybe I don't understand how syncing should work?

**Comment by steveWang** [comment]
Hi, looks like this bug was introduced when we attempted to fix a mostly unrelated issue with the client echoing back all scope synchronizations to the server. Thanks for the bug report! (fixed in commit be675edea9d968c2cc6a.)
