### ISSUE TITLE
Javascript errors

### ISSUE THREAD

**Issue by JeromeParadis** [Flotype/now#134]
Hi,

I noticed that now.js is generating multiple Javascript errors (at least using Firebug on Mac or Windows) following some socket.io calls. Before the refactor, it didn't do that. It can be reproduced from any of the 3 supplied examples in the repository (I installed 0.7.3 through npm).

Testing environment:
- nowjs 0.7.3
- socket.io 0.7.8
- node-proxy 0.5.1

Thanks for looking into this!

**Comment by steveWang** [comment]
I'm going to guess that this is with FF5, using XHR-polling?

**Comment by JeromeParadis** [comment]
Yes, Firefox 5 and from the errors it would seem that it is indeed using XHR-polling. Is there any way to decide/predict the method used for communications or a workaround to avoid these errors? in any case, it looks like a bug.

**Comment by steveWang** [comment]
By the way, this is a Socket.IO issue, and as far as I know, it's purely cosmetic. You might want to file an issue over on their end.

**Comment by ericz** [comment]
Hi @JeromeParadis,

I believed this is fixed in the latest issues of socket.io.

If you're still seeing this issue please report back.

Thanks,
Eric

**Comment by JeromeParadis** [comment]
Just got to it and yes, it was fixed. I no longer have the issue. Thanks!
