### ISSUE TITLE
Failed to install on Linux 2.6.18-194.3.1.el5PAE (CentOS release 5.6 (Final))

### ISSUE THREAD

**Issue by hacksparrow** [Flotype/now#136]
Guys, Now failed to install on a system. Could be an npm problem, could be a Now problem. Pasting the log for your reference:

[hacksparrow@web143 ~]$ npm install now

> node-proxy@0.5.2 install /home/hacksparrow/node_modules/now/node_modules/node-proxy
> make

BUILDING: C++ Component
Checking for program g++ or c++          : /usr/bin/g++
Checking for program cpp                 : /usr/bin/cpp
Checking for program ar                  : /usr/bin/ar
Checking for program ranlib              : /usr/bin/ranlib
Checking for g++                         : ok
Checking for node path                   : not found
Checking for node prefix                 : ok /home/hacksparrow
'configure' finished successfully (0.021s)
Waf: Entering directory `/home/hacksparrow/node_modules/now/node_modules/node-proxy/src/build'
[1/2] cxx: node-proxy.cc -> build/default/node-proxy_1.o
[2/2] cxx_link: build/default/node-proxy_1.o -> build/default/node-proxy.node
Waf: Leaving directory`/home/hacksparrow/node_modules/now/node_modules/node-proxy/src/build'
'build' finished successfully (0.417s)
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `LIBARCHIVE.creationtime'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`SCHILY.dev'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `SCHILY.ino'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`SCHILY.nlink'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `SCHILY.dev'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`SCHILY.ino'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `SCHILY.nlink'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`LIBARCHIVE.creationtime'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `SCHILY.dev'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`SCHILY.ino'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `SCHILY.nlink'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`SCHILY.dev'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `SCHILY.ino'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`SCHILY.nlink'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `SCHILY.dev'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`SCHILY.ino'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `SCHILY.nlink'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`LIBARCHIVE.creationtime'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `SCHILY.dev'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`SCHILY.ino'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `SCHILY.nlink'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`LIBARCHIVE.creationtime'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `SCHILY.dev'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`SCHILY.ino'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `SCHILY.nlink'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`SCHILY.dev'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `SCHILY.ino'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`SCHILY.nlink'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `SCHILY.dev'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`SCHILY.ino'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `SCHILY.nlink'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`LIBARCHIVE.creationtime'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `SCHILY.dev'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`SCHILY.ino'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `SCHILY.nlink'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`SCHILY.dev'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `SCHILY.ino'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`SCHILY.nlink'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `SCHILY.dev'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`SCHILY.ino'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `SCHILY.nlink'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`SCHILY.dev'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `SCHILY.ino'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`SCHILY.nlink'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `SCHILY.dev'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`SCHILY.ino'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `SCHILY.nlink'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`SCHILY.dev'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `SCHILY.ino'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`SCHILY.nlink'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `SCHILY.dev'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`SCHILY.ino'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `SCHILY.nlink'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`SCHILY.dev'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `SCHILY.ino'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`SCHILY.nlink'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `LIBARCHIVE.creationtime'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`SCHILY.dev'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `SCHILY.ino'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`SCHILY.nlink'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `SCHILY.dev'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`SCHILY.ino'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `SCHILY.nlink'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`SCHILY.dev'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `SCHILY.ino'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`SCHILY.nlink'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `SCHILY.dev'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`SCHILY.ino'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `SCHILY.nlink'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`SCHILY.dev'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword `SCHILY.ino'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Ignoring unknown exte           nded header keyword`SCHILY.nlink'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm" tar: Error exit delayed fr           om previous errors
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm"
npm ERR! Failed unpacking /tmp/npm-1315636792688/1315636796427-0.7533700182102621/tmp.tgz
npm ERR! couldn't unpack /tmp/npm-1315636792688/1315636796427-0.7533700182102621/tmp.tgz to /tmp/npm-1315636792688/1315636796427-0.7533700182102           621/contents
npm ERR! error installing socket.io-client@0.8.4 Error: Failed tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.75337001821026           21/contents/___package.npm"
npm ERR! error installing socket.io-client@0.8.4 exited with 2
npm ERR! error installing socket.io-client@0.8.4     at ChildProcess.<anonymous> (/home/hacksparrow/lib/node_modules/npm/lib/utils/exec.js:85:8)
npm ERR! error installing socket.io-client@0.8.4     at ChildProcess.emit (events.js:67:17)
npm ERR! error installing socket.io-client@0.8.4     at ChildProcess.onexit (child_process.js:192:12)
npm ERR! error installing socket.io@0.8.4 Error: Failed tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/cont           ents/___package.npm"
npm ERR! error installing socket.io@0.8.4 exited with 2
npm ERR! error installing socket.io@0.8.4     at ChildProcess.<anonymous> (/home/hacksparrow/lib/node_modules/npm/lib/utils/exec.js:85:8)
npm ERR! error installing socket.io@0.8.4     at ChildProcess.emit (events.js:67:17)
npm ERR! error installing socket.io@0.8.4     at ChildProcess.onexit (child_process.js:192:12)
npm ERR! error installing now@0.7.4 Error: Failed tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/_           __package.npm"
npm ERR! error installing now@0.7.4 exited with 2
npm ERR! error installing now@0.7.4     at ChildProcess.<anonymous> (/home/hacksparrow/lib/node_modules/npm/lib/utils/exec.js:85:8)
npm ERR! error installing now@0.7.4     at ChildProcess.emit (events.js:67:17)
npm ERR! error installing now@0.7.4     at ChildProcess.onexit (child_process.js:192:12)
npm ERR! Error: Failed tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1315636792688/1315636796427-0.7533700182102621/contents/___package.npm"
npm ERR! exited with 2
npm ERR!     at ChildProcess.<anonymous> (/home/hacksparrow/lib/node_modules/npm/lib/utils/exec.js:85:8)
npm ERR!     at ChildProcess.emit (events.js:67:17)
npm ERR!     at ChildProcess.onexit (child_process.js:192:12)
npm ERR! Report this _entire_ log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com
npm ERR!
npm ERR! System Linux 2.6.18-194.3.1.el5PAE
npm ERR! command "node" "/home/hacksparrow/bin/npm" "install" "now"
npm ERR! cwd /home/hacksparrow
npm ERR! node -v v0.4.11
npm ERR! npm -v 1.0.27
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/hacksparrow/npm-debug.log
npm not ok

**Comment by steveWang** [comment]
Out of curiosity, can you install other node modules via npm, or is it just this one that's failing? (also, looks like it's tar that failed, causing Socket.IO to fail, which then caused now to fail)

**Comment by hacksparrow** [comment]
Yes, I can install other module via npm. Someone told me that, I just need
to update tar, so I guess that's it - a bad tar version on the system,
which's breaking it.

**Comment by ericz** [comment]
Closing
