### ISSUE TITLE
Crash on reassign

### ISSUE THREAD

**Issue by jnordberg** [Flotype/now#138]
Assigning the same variable in a now context twice causes node crash, no errors.

to reproduce:

``` javascript
everyone.now.crash = function() {
  this.now.foo = {'some': 'thing'};
  this.now.foo = {'another': 'thing'};
};
```

seems only to happen with objects

my setup:
- osx 10.7.1
- node v0.4.11
- socket.io 0.8.4
- node-proxy 0.5.2

tested against 0.7.4 and master

**Comment by ericz** [comment]
Hi jnordberg, can you check if the commit https://github.com/Flotype/now/commit/f3830da2f4ff36b54357c5c27f81f5c80d444fd0 fixes this issue for you?

Thanks, Eric

**Comment by jnordberg** [comment]
Yup, it did.
