### ISSUE TITLE
websocket Connection Invalid/Transport End Errors

### ISSUE THREAD

**Issue by taariq** [Flotype/now#139]
We upgraded from 0.7.4 to 0.7.5 and had some new issues.

When users are having problems logging into our chat rooms, we see the following errors in our logs:

  warn  - websocket connection invalid
  info  - transport end
  warn  - websocket connection invalid
  info  - transport end
  warn  - websocket connection invalid
  info  - transport end

This happens about 10% of the users in a chat.  We had 25 people and 3 people had this problem.

However, we're still having trouble identifying why the connection is invalid. 

Taariq

**Comment by ericz** [comment]
Hi Taariq, let me know if upgrading to socket.io 0.8.4 solves the issue!

Eric

**Comment by taariq** [comment]
Thanks Eric. We're testing on Staging.
Will do.

-----Original Message-----

**Comment by reedlaw** [comment]
This is working for me locally but I get the error on Heroku:

```
2011-09-18T01:47:50+00:00 heroku[router]: Error H13 (Connection closed without response) -> GET geomon.herokuapp.com/socket.io/1/websocket/11652186541056559304 dyno=web.1 queue= wait= service= status=503 bytes=
2011-09-18T01:47:50+00:00 app[web.1]:    warn  - websocket connection invalid
```

I am using now 0.7.5 and socket.io 0.8.4

**Comment by sridatta** [comment]
@reedlaw: Your problem may be unrelated to this. Heroku does not support Websockets at all. You can get around this by listing the transports you want to enable (and excluding websockets from the list): 
`nowjs.initialize(server, {socketio: {transports: ['xhr-polling', 'jsonp-polling', 'htmlfile']}});`

**Comment by reedlaw** [comment]
Thank you @sridatta, that works.

**Comment by ericz** [comment]
@taariq,

The most likely cause of these issues is client firewalls / antivirus security software. See https://github.com/LearnBoost/socket.io/wiki/Socket.IO-and-firewall-software

**Comment by ericz** [comment]
Closing. Feel free to reopen if there are additional issues.

**Comment by taariq** [comment]
Thanks.  No worries.
T.

On 1/16/12 12:40 PM, "Eric Zhang"
<reply+i-1630104-158632e27cb933b56360624ca0a0639ab6d31f02-701864@reply.gith
ub.com> wrote:
