### ISSUE TITLE
Pass Socket.IO control?

### ISSUE THREAD

**Issue by alax** [Flotype/now#14]
Hey guys, I was wondering if there's any way you can make a way to allow us to pass options to Socket.IO via Now? Basically, I just want to suppress Socket's logging and use my own, but currently, I can't do that without modifying NowJS or Socket.

Thanks!

**Comment by ericz** [comment]
Hey alax,

Surpressing Socket.IO's logging is coming soon. We're not sure how much of the socket.io interface to expose to the user because we don't want to overcomplicate things. I'll let you know what develops

**Comment by alax** [comment]
Okay, great, thanks!
