### ISSUE TITLE
When will NowJS be able to read the response and request objects?

### ISSUE THREAD

**Issue by felixchan** [Flotype/now#148]
It's really painful not to be able to access the user's session.

**Comment by yuchi** [comment]
Probably [this link](http://fzysqr.com/2011/02/28/nodechat-js-using-node-js-backbone-js-socket-io-and-redis-to-make-a-real-time-chat-app/) can help you to build a workaround and to probably propose an implementation for a simpler API to now.js. Remember to look also Update 2 and Update 3 where Justin Slattery implements the authenticated sockets.

**Comment by ericz** [comment]
@felixchan

You can access the session data by finding the connection sessionId:

`var id = unescape(this.user.cookie['connect.sid']));`

With which you can access the session date if you are using sessions in express.

**Comment by ericz** [comment]
Because of the different paradigm of request / response as opposed to realtime data communication, it's not possible to access the request/response object (as there is no concept of request or response). Use the technique above you can access the session data store. 

Closing
