### ISSUE TITLE
Examples do NOT work in Chrome

### ISSUE THREAD

**Issue by zanematthew** [Flotype/now#150]
Trying the autocomplete example http://nowjs.com/examples and it does not work in Chrome, getting the error below:

Uncaught TypeError: Object #<Object> has no method 'getGuess'

**Comment by steveWang** [comment]
It should probably have `now.getGuess($('#autocomplete').val());` wrapped inside a `now.ready` block.

**Comment by ericz** [comment]
Yep that appears to be the issue

**Comment by zanematthew** [comment]
Hey I was going to do a pull request and adjust it, but it appears that this is fixed, I'm going to close it.
