### ISSUE TITLE
Redeclaration of a Function in the now namespace fails

### ISSUE THREAD

**Issue by toha** [Flotype/now#152]
I declared a function on the client

now.foo = function() {
  console.log("foo");
};

and I can use it on the server with

user.now.foo();

But, if i redeclare the function in the client

now.foo = function() {
  console.log("bar");
};

I cannot access it from the server anymore:

TypeError: Property 'foo' of object #<Object> is not a function.

On first declaration, nowjs sends:
5:::{"name":"rv","args":[{"now.foo":{"fqn":"now.foo"}}]}

and on the second declaration:
5:::{"name":"rv","args":[{"now.foo.fqn":"now.foo"}]}

**Comment by ericz** [comment]
Reproduced. Fixing...

**Comment by ericz** [comment]
Hi toha, this issue has been fixed in the latest GH master.

Eric

**Comment by ericz** [comment]
Additionally I've updated our test suite to ensure this does not go uncaught again.
