### ISSUE TITLE
Using now.js with Appcelerator

### ISSUE THREAD

**Issue by scottburch** [Flotype/now#159]
I have found the way to use now.js with Appcelerator and wanted to document it somehow so that others can find it.

This is from theindex.html in my desktop project

```
    <script src="http://localhost:3000/nowjs/now.js"></script>
    <script>var nowjs = nowInitialize('http://localhost:3000',{});</script>
```

I'm not sure why 'now' does not work other than it calls the wrong uri and may setup two objects.  But, using the noconflict method (called initialize) works great for me.

Instead of now.xxxx use nowjs.xxxx

**Comment by steveWang** [comment]
You should probably set autoHost in your server-side config to false, in this case. What URI does the autohosted `now` call?

**Comment by ghost** [comment]
I also have this problem and trying to figure out a solution, its a socket.io problem I believe.

**Comment by ericz** [comment]
If there are further issues with this, try the google group http://groups.google.com/group/nowjs?pli=1
