### ISSUE TITLE
remote callback not being called

### ISSUE THREAD

**Issue by scottburch** [Flotype/now#16]
SERVER

everyone.now.getData = function(callback) {
    callback(getData())
}

CLIENT

```
now.ready(function() {
    now.getData(function(data) {
        fillTree(treePanel.getRootNode(), data);
    })
})
```

I took a wireshark trace and I see the instructions to call the callback (I think) but the callback never gets called.  The documentation does not cover this well.

**Comment by dvv** [comment]
Please, carefully look at the example -- you need to add a second callback at client-side.
Just use a noop -- `function(){}`

**Comment by ericz** [comment]
Hi scottburch.

If you are running NowJS version < 0.3, then dvv is correct and you will need to use an noop. 

However if you are using the latest npm version (0.3.0), I have tested your code and it works for me. Can you provide more information about the exact code and version of NowJS you're using?

Thanks, Eric

**Comment by scottburch** [comment]
I wrote a minimal example of what I am doing (since I put this in a  larger project) and it does work fine.  I will try to remove a piece at a time until I figure out what is causing it to fail. I will post here when I find it.  Thanks.  

I was not sure I was using it correctly.

**Comment by scottburch** [comment]
Ok, found it.
I am using ExtJS and loading ext-base.js causes it to fail.  Works if I remove it
