### ISSUE TITLE
Not installing on windows

### ISSUE THREAD

**Issue by anandgeorge** [Flotype/now#161]
Have installed it on Ubuntu 10.04 and had to use sudo for installation. Now with Windows XP, Node version 0.6.3, installation fails with EACCES, permission denied. Can I get some help.

**Comment by ericz** [comment]
Hi anandgeorge,

Are you using the instructions for Windows installation from here: http://blog.nowjs.com/running-nowjs-natively-on-windows ?

**Comment by ericz** [comment]
`npm install now` on Windows definitely will not work due to the binary node-proxy dependency

**Comment by ericz** [comment]
Closing issue. Let me know if you are still having trouble with this issue.
