### ISSUE TITLE
[Feature Request] Add a way to remove groups

### ISSUE THREAD

**Issue by goldfire** [Flotype/now#163]
Since groups stay in memory even after everyone in the group disconnects (or at least this is the behavior I've been experiencing), you could end up with millions of groups sitting around in memory with nobody connected. Adding something like the below would be helpful.

nowjs.removeGroup(groupName);

**Comment by Peterfly** [comment]
yes, it sounds like a good improvement. but then only the server side should be allowed to call it. otherwise, a client may easily disconnect other clients in the same group.

**Comment by goldfire** [comment]
Yes, good point.

**Comment by Peterfly** [comment]
already refined it on the branch removegroup. it may come out later

**Comment by ericz** [comment]
Hi goldfire, 

This functionality is now in the github master. It'll be released with the next version on npm.

If you're on the github master, you can use `nowjs.removeGroup(groupName);`

Thanks to @steveWang @Peterfly  for helping with this.
