### ISSUE TITLE
0.8 Update Support

### ISSUE THREAD

**Issue by dortzur** [Flotype/now#173]
I know it was just released, but i really need the ability send parameters to socket.io available only since 0.8.
any idea when we'll the update?

**Comment by steveWang** [comment]
If you're talking about configuration options, [that's been around since at least 0.6.1](http://nowjs.com/doc/symbols/nowjs#.initialize) -- `options.socketio` should hold any parameters you want to pass to Socket.IO.

**Comment by dortzur** [comment]
i'm talking about setting parameters from the client side

[image: image.png]

On Tue, Jan 17, 2012 at 10:12 PM, Steve Wang <
reply@reply.github.com

**Comment by steveWang** [comment]
That should be available via `options.client.socketio`.

Alternatively, if you don't use autohosting, you can pass in an options object to nowInitialize that has a `socketio` property.

**Comment by ericz** [comment]
windows branch is now v0.8.1!

**Comment by dortzur** [comment]
Thanks :-)
On Jan 22, 2012 11:11 PM, "Eric Zhang" <
reply@reply.github.com>
wrote:
