### ISSUE TITLE
Can't use on windows?

### ISSUE THREAD

**Issue by LordZardeck** [Flotype/now#174]
I tried using npm to install nowjs on windows but it came up with an error because node-proxy tried to call the command "make". Is there any way to use nowjs on windows?

**Comment by steveWang** [comment]
https://github.com/Flotype/now/tree/windows

Needs updating, though. I'll bug Eric about that.

**Comment by ericz** [comment]
Here's the tutorial: http://blog.nowjs.com/running-nowjs-natively-on-windows
