### ISSUE TITLE
socket.io 0.9.1-1 blows up nowjs - urgent

### ISSUE THREAD

**Issue by henryoswald** [Flotype/now#182]
Hi this is fairly urgent, the latest version of socket.io 0.9.1-1 breaks now with the connection dropped every 60 seconds or so calling now.disconnect. I have tested in in ubuntu 10.4 and osx 10.7 both using node 0.6.8. I would for the moment recommend changing the package.json to "socket.io": "== 0.8.7" just to get it working.

Thanks

Henry

**Comment by scanferla** [comment]
This also happens to me!

I believe it has something to do with this:

```
   debug - emitting heartbeat for client 21318470431441253076
   debug - websocket writing 2::
   debug - set heartbeat timeout for client 21318470431441253076
   debug - got heartbeat packet
   debug - cleared heartbeat timeout for client 21318470431441253076
   debug - set heartbeat interval for client 21318470431441253076
   debug - emitting heartbeat for client 754031648847333126
   debug - websocket writing 2::
   debug - set heartbeat timeout for client 754031648847333126
   info  - transport end
```

**Comment by steveWang** [comment]
Known issue on Socket.IO's end: https://github.com/LearnBoost/socket.io/issues/777

Evidently a _temporary_ hack is to set the close timeout to something arbitrarily high, e.g. `nowjs.initialize(app, {socketio: {'close timeout': 86400}})`.

Should be fixed eventually by them.

**Comment by scanferla** [comment]
Thanks, @steveWang :)

**Comment by scanferla** [comment]
Check this comment by guille: https://github.com/LearnBoost/socket.io/issues/777#issuecomment-4358734

You can just "npm update" and you will get 0.9.0 again, which works.

**Comment by steveWang** [comment]
Ah, cool. Will close for now, since it'll presumably be fixed on Socket.IO's end when the version is bumped again..
