### ISSUE TITLE
client side callbacks do not work with ExtJS

### ISSUE THREAD

**Issue by scottburch** [Flotype/now#19]
loading ext-base will cause callbacks not to be called

opening another ticket because I accidentally closed #17

**Comment by scottburch** [comment]
Here is the code

SERVER
everyone.now.getData = function(callback) {
    callback(getData());
}

CLIENT
<!doctype html>

<html>
    <head>
        <script type="text/javascript" src="nowjs/now.js"></script>
        <script type="text/javascript" src="vendors/ext/ext-base.js"></script>
        <script>
            now.ready(function() {
                now.getData(function(data) {
                    console.log('done')
                })
            })
        </script>

```
</head>
<body>
</body>
```

</html>

**Comment by ericz** [comment]
Fixed

**Comment by scottburch** [comment]
I just tested in my ExtJS app.  Works fine.  Thanks
