### ISSUE TITLE
undefined arguments

### ISSUE THREAD

**Issue by dvv** [Flotype/now#20]
Hi!

L#181 nowServerLib.js -- bad things happen if theArgs[i] is null/undefined/non-object

--Vladimir

**Comment by ericz** [comment]
Thanks dvv, will fix this today

**Comment by ericz** [comment]
Hey dvv,

Turns out it's not a problem if theArgs[i] is primitive or undefined (as hasownproperty still exists) but IS a problem if it's null, so I have added a null check. Thanks!

**Comment by dvv** [comment]
Yep. Anytime when one uses `typeof obj === 'object'` he must use `obj && typeof obj === 'object'`.
Wouldn't you check if there can the same issues in the code, as you know it the best?
TIA,
--Vladimir
