### ISSUE TITLE
Error: Cannot find module 'now'

### ISSUE THREAD

**Issue by NextZeus** [Flotype/now#225]
npm install successed! but Error occured when i run express app

**Comment by NextZeus** [comment]
var nowjs = require("now");
var server = global.server;
var everyone = nowjs.initialze(server);
var app = express();

**Comment by ghost** [comment]
@NextZeus the now package on NPM is from https://zeit.co/now

this project looks deader than dead. it is ded.

**Comment by alaa-eddine** [comment]
if you are looking for an alternative I'm maintaining a project called [eureca.io](https://github.com/Ezelia/eureca.io/)  with similar functionality and some additional features.

I started it 5 years ago when Flotype/now died and I'm still maintaining it :)
