### ISSUE TITLE
Make example app more prominent: showcase the various patterns of nowjs usage

### ISSUE THREAD

**Issue by DTrejo** [Flotype/now#25]
People live off examples.

Would be great if you had a sample app which laid out all the patterns, with an easy step by step 

```
<install node>
<install npm>
git clone nowjs
node server.js
```

to attract both newcomers to node and newcomers to nowjs and the ways it can be used.

**Comment by ericz** [comment]
Interesting. I need to get blogging!

**Comment by ericz** [comment]
Closing
