### ISSUE TITLE
NowJS is improperly served when it is injected after the document has loaded.

### ISSUE THREAD

**Issue by humanchimp** [Flotype/now#26]
If you include the /nowjs/now.js script in the HTML, everything works fine.  The problem arises if you want to inject the script after the page has loaded for some reason.

Suggested fix in lib/nowServerLib.js at line 289

<pre>
-      if(request.url === "/nowjs/now.js") {
+      if(request.url.split('?')[0] === "/nowjs/now.js") {
</pre>

**Comment by ericz** [comment]
Thanks for bug report and fix.
