### ISSUE TITLE
Error with latest version of Express

### ISSUE THREAD

**Issue by nsmeta** [Flotype/now#30]
Hello,
I'm having this error every time I load a page, regardless of if I have included now.js script on client-side. My guess would be, it's because of latest version of Connect Middleware; since they have updated their APIs.
I'm on Mac OS, Google Chrome(though, the same error appears with Firefox as well).
I would really appreciate your help.

Thank You.

```
 { stack: [Getter/Setter],
 arguments: 
 [ 'indexOf',
 { stack: [Object],
   connections: 6,
   allowHalfOpen: true,
   watcher: [Object],
   _events: [Object],
   httpAllowHalfOpen: false,
   match: [Object],
   lookup: [Object],
   settings: [Object],
   redirects: {},
   isCallbacks: {},
   viewHelpers: [Object],
   dynamicViewHelpers: [Object],
   errorHandlers: [],
   route: '/',
   routes: [Object],
   router: [Getter],
   __usedRouter: true,
   type: 'tcp4',
   fd: 9 } ],
 type: 'undefined_method',
 message: [Getter/Setter] }
 TypeError: Object #<HTTPServer> has no method 'indexOf'
 at HTTPServer.<anonymous> (/Users/Me/Work/testing/app.coffee:11:19)
 at HTTPServer.<anonymous>              (/usr/local/lib/node/.npm/now/0.3.2/package/lib/nowServerLib.js:293:31)
at HTTPServer.<anonymous> (/usr/local/lib/node/.npm/socket.io/0.6.16/package/lib/socket.io/listener.js:35:20)
at HTTPServer.emit (events.js:67:17)
at HTTPParser.onIncoming (http.js:1108:12)
at HTTPParser.onHeadersComplete (http.js:108:31)
at Socket.ondata (http.js:1007:22)
at Socket._onReadable (net.js:677:27)
at IOWatcher.onReadable [as callback] (net.js:177:10)
```

**Comment by sridatta** [comment]
Thanks for reporting the issue. Looking into this right now.
--Sridatta

**Comment by nsmeta** [comment]
Thanks for the quick response!

NowJS v0.3.2
Connect v1.2.1
Express v2.2.0

**Comment by sridatta** [comment]
I'm at the same versions as you and I'm unable to reproduce this problem on the Express chat example found here (https://github.com/Flotype/now/tree/master/examples/express_example). Can you tell me if this example is working for you?

**Comment by nsmeta** [comment]
Everything works. Well, this is embarrassing; I've found what seems to be the problem.
I'm using a custom extension to the Array object, below(in CoffeeScript).
<code>
     Array::remove = (e) -> @[t..t] = [] if (t = @.indexOf(e)) > -1
</code>

I apologize for this; my bad. Thank you so much for helping me out.

**Comment by sridatta** [comment]
No problem. I'm glad you found the bug.
