### ISSUE TITLE
Socket.io not loaded in Internet Explorer

### ISSUE THREAD

**Issue by straps** [Flotype/now#31]
In this test I've written
https://github.com/straps/nodejs-demos/tree/master/24-express-nowjs

I get an error loading http://IP:8080/client.html with Internet Explorer: io is not defined

Example works well on Chrome and Firefox...am I missing something?

Thanks

**Comment by ericz** [comment]
Looking into this now. Thanks for the report.

**Comment by straps** [comment]
Solved, cache related
https://github.com/Flotype/now/issues/closed#issue/22

Thanks
