### ISSUE TITLE
Expose socket.io request object

### ISSUE THREAD

**Issue by ggoodman** [Flotype/now#32]
In order to tie now clients to the browsing session, it would be nice to have access to the request object and thus to the client's cookies.

**Comment by numan** [comment]
+1 I have a use case where this would be really useful.

**Comment by ericz** [comment]
Interesting. Sounds like it would be useful to make a connect middleware in that case. I'll look into this and see what we can do.

**Comment by sridatta** [comment]
Implemented this in latest repo code. Expect to see in it in 0.5.0 npm release.

**Comment by dvv** [comment]
Wonder if you could point to the commit. TIA

**Comment by sridatta** [comment]
latest commit: https://github.com/Flotype/now/commit/c993085b7890e01f90d8161da2a497e738d5560d

**Comment by dvv** [comment]
Hmm. This commit is about "move socketio options into options", which seems irrelevant to the subj, no?
