### ISSUE TITLE
Extend sample with available users

### ISSUE THREAD

**Issue by jettro** [Flotype/now#34]
Hi,
is it possible to extend the sample with a list of people that are online? I am not very successful at creating my own sample with a shared list of available people. Would be nice to have this as an addition to the current sample. I guess you can create it in 20 minutes :-).

thanks

**Comment by sridatta** [comment]
Sorry, this is not an _issue_ with NowJS. Feel free to seek help on this on our IRC channel (#nowjs on Freenode).

**Comment by jettro** [comment]
I know it is not an issue, more a feature request :-). Wanted to label it as such, but could not find how to do just that. Would be nice to have a forum or something, not that much of an IRC guy.
