### ISSUE TITLE
flashing

### ISSUE THREAD

**Issue by dvv** [Flotype/now#38]
Hi!

At initial page load regardless of used socket.io transport an embedded flash object appears and then disappeares, causing unpleasant flashing. Wonder if this is pure socket.io issue?

TIA,
--Vladimir

**Comment by ericz** [comment]
Strange, I haven't seen this before? This should be a pure socket.io issue as we don't modify the way they handle their flash player.

**Comment by dvv** [comment]
I should be pinging them then.

**Comment by ericz** [comment]
https://github.com/LearnBoost/Socket.IO/issues/130
