### ISSUE TITLE
now.ready

### ISSUE THREAD

**Issue by dvv** [Flotype/now#39]
Hi!

Opera/9.80 (X11; Linux i686; U; ru) Presto/2.7.62 Version/11.01

Resulting now.js, L671 -- here can be `ready == null` -- this causes exception.
If I `try/catch` this line, `now.ready` handler is called twice.

TIA,
--Vladimir

**Comment by ericz** [comment]
Strange, `ready` should never be null on initial connection?

**Comment by dvv** [comment]
It's ok with current master. Can be closed

**Comment by dvv** [comment]
Sorry, have to reopen. Opera/9.80 (X11; Linux i686; U; ru) Presto/2.7.62 Version/11.01 -- `now.ready()` is spawned twice. Reason unknown so far...

**update**: Finally proven unrelated to now.js. Very well. Closing...
