### ISSUE TITLE
no way to set priority of and/or disable socket.io transport types

### ISSUE THREAD

**Issue by tommedema** [Flotype/now#42]
Some developers will want a different priority of transport types.

Others will want to completely disable certain methods as they would be too laggy for the application to function or ask too much from the server.

Thus, it has to be possible to set this transport order and disable certain transports completely.

**Comment by ericz** [comment]
Hi tom, this has been fixed in version v0.5. You can pass in an options.socketio object to initialize. This object will be passsed straight into socketio initialization. For example:

```
 nowjs.initialize(httpServer, {socketio: {transports: ['websocket', 'htmlfile']}})
```
