### ISSUE TITLE
documentation lacks new clientWrite and socketio options

### ISSUE THREAD

**Issue by tommedema** [Flotype/now#46]
The documentation lacks the new clientWrite and socketio options.

**Comment by sridatta** [comment]
We seemed to have missed that. I'll write those in tonight!

**Comment by ericz** [comment]
Obviously sridatta didn't write the documentation on the night of April 10th. We'll get this in there

**Comment by tommedema** [comment]
Documentation also incorrectly says that the connected events on the server return a clientId rather than a client.

**Comment by ericz** [comment]
Finally this can be put to rest. Also the ' incorrectly says that the connected events on the server return a clientId rather than a client.' has been fixed in an earlier commit.
