### ISSUE TITLE
now.ready is not a Function (Firefox 3.6.16 - Firefox for Ubuntu, canonical 1.0)

### ISSUE THREAD

**Issue by simaob** [Flotype/now#47]
Hi guys,

first of all congratulations for your work, this is really awesome! =) 

We at my workplace are developing with a small chat and a map that can be edited and in Firefox 3.6.16 for Ubuntu I am getting an error that states:

now.ready is not a function.

The strange thing is that this is working in Google Chrome in the same machine and with the same server.

In Firefox 4 in Mac OSx it seems to be working alright.

Any idea of what might be wrong? Cheers!

**Comment by dvv** [comment]
how fresh is the code you use? npm? or current master?

**Comment by simaob** [comment]
We're using the code from npm.

**Comment by dvv** [comment]
Please, try current master. The issue has been fixed circa yesterday.

**Comment by ericz** [comment]
Any luck simaob? Definitely an issue regarding now.ready has been fixed in master

**Comment by simaob** [comment]
Hi guys,

thank you for your reply. We managed to get it working. =) I'm not sure if anyone updated the version of now or if fixed any issue on our code, but it is now working. I think it was probably the latter.

Anyway if you want to take a look at what we've done it's here:

http://labs.unep-wcmc.org/

Cheers!
