### ISSUE TITLE
express chat example occasional missing/double messages

### ISSUE THREAD

**Issue by devcurmudgeon** [Flotype/now#48]
this _may_ be a duplicate of pbcomm's issue #36. 

the following behaviour happens infrequently - i've not been able to establish what triggers it. i'm using 0.5.0 w Safari

1) after starting the express example, create user1 and send a message "hi"
2) create user2 and send a message from it: "ho"

if the bug is happening - 
3) the "ho" message doesn't appear in user1's window
4) subsequent messages from both user1 and user2 appear twice in user1's window

**Comment by ericz** [comment]
We've seen a similar issue before. Do you know the transport type that is associated with each connection? (It should have been printed in server console by socket.io)

**Comment by devcurmudgeon** [comment]
afaik the only transport that socket.io ever creates for my setup (node in local shell, safari) is "websocket"

**Comment by ericz** [comment]
This is incredibly strange. I'll try to reproduce it on a mac (can't on Safari for windows?)

**Comment by devcurmudgeon** [comment]
i'm closing this, on the basis that i've not been able to reproduce since pulling code a few days ago. i'll reopen if it happens again
