### ISSUE TITLE
opera or xhr-polling quirks

### ISSUE THREAD

**Issue by dvv** [Flotype/now#55]
Hi!

The following chunk of code:

```
// ...
now.ready(function() {
  console.log('NOW READY');
  var operaSucksOrXHRPollingSucksOrWhat = false;
  now.getContext(id, function(response) {
    if (operaSucksOrXHRPollingSucksOrWhat) return;
      operaSucksOrXHRPollingSucksOrWhat = true;
      console.log('GOT CONTEXT', response);
      // ...
```

illustrates the problem I previously described in [#39](https://github.com/Flotype/now/issues/39)

`now.ready` indeed is called once, but without the fuser I get two `GOT CONTEXT` lines in the console, which means the callback for my custom `now.getContext` is called twice. This quirk I noticed only when testing in Opera which fallbacks to xhr-polling socket.io method.

Can anyone confirm this behavior?

TIA,
--Vladimir

**Comment by ericz** [comment]
I have reproduced it.

It connects to the server twice, and thus all actions get doubled. Lets see whats causing it....

**Comment by dvv** [comment]
Interesting to check, whether it's xhr-polling, or Opera, who's failing?

**Comment by ericz** [comment]
Actually it seems like this is an issue with the internal dependency loaded callback being called twice. 

This issue should be fixed in master.

**Comment by dvv** [comment]
Worth to mention: if the server downs and ups, `now.ready` is re-called if reconnection enabled. So anyone who puts singleton stuff into `now.ready` (my situation: `Backbone.history.start()`), be warned that you shouldn't.

**Comment by ericz** [comment]
Hmm I should get that in the documentation

**Comment by juzerali** [comment]
@ericz: Is this resolved or just closed? Coz I am facing this issue.
