### ISSUE TITLE
Node 2 Node Connections?

### ISSUE THREAD

**Issue by PaulFreund** [Flotype/now#57]
Hi, is it intended to support Client-Server connections between multiple Node Instances in the future? this would really be a great feature for Clustering and alike :)

**Comment by ericz** [comment]
Yes we are working on this product, however it will licensed separately from the main nowjs branch.

**Comment by PaulFreund** [comment]
What do you mean with a separate license? There is no license at all at the time ( none that I could find ). Do you want to charge users in the future?
