### ISSUE TITLE
bug/regression: passing multiple functions as arguments does not work properly.

### ISSUE THREAD

**Issue by humanchimp** [Flotype/now#60]
If you pass multiple references to functions into a method on the now object, nowjs gets confused.  It does not reliably (or at all) call back the correct function.  I have created a trivial example that can be downloaded [here](http://humanchimp.kodingen.com/bugs/bug1.zip).  In your terminal, you can <code>cd</code> to the directory, and then type <code>./run</code>.  Alternatively, you can do <code>node bug1.js</code>.

Using nowjs 0.5.1, I get:

<pre><code>expected output:
first
second
third
actual output
(3) third<code></pre>

**Comment by sridatta** [comment]
This was an issue about how we were naming/keeping track of anonymous functions. I committed a fix to the repo and npm just now.
