### ISSUE TITLE
Accessing reference to now scope causes strange behavior

### ISSUE THREAD

**Issue by tommedema** [Flotype/now#62]
When saving a reference to the now scope of a client for later use on the server side, like so:

```
clients[name] = {now: this.now, connectedClient: null};
```

rather strange behavior is seen when using this now scope to call another server-sided function

if someone does the following somewhere else:

```
client1 = clients[someName];
client1.now.someServerNowMethod();

everyone.now.someServerNowMethod = function() {
     //the problem: here, "this" equals the actual now scope, even though it should be this.now.. aka, this.now is undefined when called this method is called in the above way
}
```

So, "this"  equals what should be "this.now" when called like this.

**Comment by ericz** [comment]
This should've have been fixed in a recent version of the code. I'm going to look into what happened...

**Comment by tommedema** [comment]
I should mention that I update with NPM.

**Comment by ericz** [comment]
I have replicated this bug. Fixing...

**Comment by ericz** [comment]
Found bug. Fixing...

**Comment by ericz** [comment]
Fixed! Will be pushed to npm in next few hours

**Comment by tommedema** [comment]
You rock!
