### ISSUE TITLE
websocket client does not invoke connect callback

### ISSUE THREAD

**Issue by johnou** [Flotype/now#64]
--debug-brk=56668 /home/developer/workspaces/test/app.js
debugger listening on port 56668
23 Apr 15:24:22 - Your node instance does not have root privileges. This means that the flash XML policy file will be served inline instead of on port 843. This will slow down initial connections slightly.
23 Apr 15:24:22 - socket.io ready - accepting connections
127.0.1.1 - - [Sat, 23 Apr 2011 12:24:28 GMT] "GET / HTTP/1.1" 200 897 "" "Mozilla/5.0 (X11; U; Linux i686; en-GB; rv:1.9.2.9) Gecko/20100825 Ubuntu/10.04 (lucid) Firefox/3.6.9"
127.0.1.1 - - [Sat, 23 Apr 2011 12:24:28 GMT] "GET /js/protaculous-min.js HTTP/1.1" 304 - "http://localhost.sulake.com:3000/" "Mozilla/5.0 (X11; U; Linux i686; en-GB; rv:1.9.2.9) Gecko/20100825 Ubuntu/10.04 (lucid) Firefox/3.6.9"
23 Apr 15:24:29 - Initializing client with transport "xhr-multipart"
23 Apr 15:24:29 - Client 6729125350248069 connected
Connected: undefined
127.0.1.1 - - [Sat, 23 Apr 2011 12:24:36 GMT] "GET / HTTP/1.1" 200 897 "" "Mozilla/5.0 (X11; Linux i686) AppleWebKit/534.31 (KHTML, like Gecko) Chrome/12.0.746.0 Safari/534.31"
127.0.1.1 - - [Sat, 23 Apr 2011 12:24:36 GMT] "GET /js/protaculous-min.js HTTP/1.1" 304 - "http://localhost.sulake.com:3000/" "Mozilla/5.0 (X11; Linux i686) AppleWebKit/534.31 (KHTML, like Gecko) Chrome/12.0.746.0 Safari/534.31"
23 Apr 15:24:36 - Initializing client with transport "websocket"
23 Apr 15:24:36 - Client 45594913978129625 connected
127.0.1.1 - - [Sat, 23 Apr 2011 12:24:36 GMT] "GET /favicon.ico HTTP/1.1" 404 - "" "Mozilla/5.0 (X11; Linux i686) AppleWebKit/534.31 (KHTML, like Gecko) Chrome/12.0.746.0 Safari/534.31"
23 Apr 15:24:46 - Client 6729125350248069 disconnected
23 Apr 15:24:50 - Client 45594913978129625 disconnected

**Comment by johnou** [comment]
Using Chromium 12.0.746.0 (82790) I found that after it connects to the server the connect callback is not invoked, yet it is for Firefox using the xhr-multipart transport.

**Comment by johnou** [comment]
https://gist.github.com/938746

**Comment by ericz** [comment]
Do you have the same issue with the hello_world example chat?

**Comment by ericz** [comment]
@johnou I'm still unable to reproduce this problem.

If you'd like more assistance, please email me, eric@nowjs.com

Thanks!

**Comment by johnou** [comment]
@ericz sorry, I didn't see the email notification for your first question. Strangely enough I am unable to reproduce this bug as well. If I do manage I'll make sure to collect more information and let you know. Thanks for your time!
