### ISSUE TITLE
Does it work with Nodester?

### ISSUE THREAD

**Issue by balupton** [Flotype/now#65]
Tried deploying my now.js app https://github.com/balupton/nowpad to nodester, and doesn't work.

Has anyone else found this? Or has anyone gotten a now.js app working with nodester?

Cheers :)

Here is the nodester issue btw: https://github.com/nodester/nodester/issues/114

**Comment by ericz** [comment]
I know for a fact that people have used nowjs on nodester successfully before. I haven't personally tried though

**Comment by balupton** [comment]
Doh! My bad, was missing the `ejs` package. Thought express included that. Sorry for the inconvenience. THANKYOU!

**Comment by ericz** [comment]
Glad you got it to work
