### ISSUE TITLE
Causes Safari 5 on OSX to Crash

### ISSUE THREAD

**Issue by balupton** [Flotype/now#69]
Accessing the `express_example` in Safari 5 will cause Safari 5 to crash. Nothing is outputted to the server log.

> $ cd express_example/
> $ node app.js 
> Express server listening on port 8080
> 25 Apr 11:28:00 - Your node instance does not have root privileges. This means that the flash XML policy file will be served inline instead of on port 843. This will slow down initial connections slightly.
> 25 Apr 11:28:00 - socket.io ready - accepting connections

**Comment by 3rd-Eden** [comment]
Disable Auto Proxy Discovery in your network settings, it's a known issue in safari that it will crash if when using websockets and proxy detection

**Comment by ericz** [comment]
Thanks @3rd-Eden
