### ISSUE TITLE
working together with expressjs lib

### ISSUE THREAD

**Issue by gitfy** [Flotype/now#8]
Hi,
Do you have an example of nowjs working with express js library. I see you the nowjs API takes a httpserver, but when i replaced it with the server object from express, it throws an exception....

Is it possible to get this working together with express js ?

I did a very basic test, but i will dig deep into this to see what can be done as well.

**Comment by ericz** [comment]
Express compatibility now exists. Example will go up soon.

Thanks,
Eric

**Comment by chrisabrams** [comment]
Any chance you can post up an example soon?

**Comment by steveWang** [comment]
https://github.com/Flotype/now/tree/master/examples/express_example ?
