### ISSUE TITLE
Client-side now.disconnect event function

### ISSUE THREAD

**Issue by tommedema** [Flotype/now#83]
There's a now.ready function for when a connection to the now server has been established. The same event function should be available for when the connection was closed (and preferably with an error code indicating why the connection was closed).

**Comment by ericz** [comment]
Yep we do plan on implementing this along with reconnection support

**Comment by ericz** [comment]
Hi tom,

Reconnection support hasn't been completed yet (I'm integrating with socket.io 0.7 right now) but the disconnect event already exists in the github master.

```
 now.core.on('disconnect', function(){
      // Called upon disconnection, no automatic reconnection right now
 });
```

**Comment by tommedema** [comment]
@ericz, thanks. May I ask why the syntax appears different from now.ready ? Other than that, this is exactly what I meant.

**Comment by ericz** [comment]
now.ready is a alias for now.core.on('ready') 

We don't want to add a now.disconnect because it adds more cruft to now namespace

Eric

**Comment by tommedema** [comment]
Right, personally I would remove the alias too.

2011/5/9 ericz <
reply@reply.github.com>
