### ISSUE TITLE
when i click stop in the browser it disconnects from now

### ISSUE THREAD

**Issue by shimondoodkin** [Flotype/now#94]
intuitive behavior anti pattern:
somehow web sockets io decided to use XHR , i saw an hourglass cursor very long time , so i clicked stop 
(because i saw the page is loaded fully but it still tells me to wait).
when i click stop in the browser it disconnected the page from now.
then  i clicked in the simple chat on send message button and it did not worked.

at last i expected it to reconnect and execute the send message request. + maybe to preserver the client id and maybe maybe to execute the stack of unsent commands that is kept for some time on the server.

other solution is to change the cursor to default.

**Comment by 3rd-Eden** [comment]
Was it a webkit based browser?

**Comment by shimondoodkin** [comment]
it was a chrome i installed a week ago.

**Comment by 3rd-Eden** [comment]
If now js updates to latest socket.io version this would be resolved

~ Arnout Kazemier

**Comment by shimondoodkin** [comment]
thanks

**Comment by ericz** [comment]
Thanks 3rd-Eden we'll test and bump up the version number =p

**Comment by 3rd-Eden** [comment]
Be sure to check if it solved this issue ;). But my I guess so as the in 0.6.17 the XHR connection was made before onload in webkit based browser which triggers the load indicators even when the browser is finished loading.. And pressing top always causes all current requests to top..

**Comment by shimondoodkin** [comment]
this issure is resolved
